# Generated by Django 5.2.8 on 2025-11-27 09:19

import django.db.models.deletion
import ideas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_delete_reservation_idea_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='idea_images/', validators=[ideas.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ideas.idea')),
            ],
        ),
    ]
