# Generated by Django 6.0 on 2025-12-12 07:20

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_activationcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activationcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='activationcode',
            name='uid',
        ),
        migrations.AddField(
            model_name='activationcode',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'E-mail')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='activationcode',
            name='code',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='activationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activationcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('both', 'Oba')], default='email', max_length=10),
        ),
        migrations.AddIndex(
            model_name='activationcode',
            index=models.Index(fields=['code', 'channel'], name='ideas_activ_code_927356_idx'),
        ),
        migrations.AddIndex(
            model_name='activationcode',
            index=models.Index(fields=['expires_at'], name='ideas_activ_expires_010dba_idx'),
        ),
    ]
