# Generated by Django 5.2.8 on 2025-12-15 11:23

import django.db.models.deletion
import ideas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_remove_reservation_customer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activationcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kod aktywacyjny', 'verbose_name_plural': 'Kody aktywacyjne'},
        ),
        migrations.AlterModelOptions(
            name='idea',
            options={'verbose_name': 'Pomysł', 'verbose_name_plural': 'Pomysły'},
        ),
        migrations.AlterModelOptions(
            name='ideaimage',
            options={'verbose_name': 'Zdjęcie pomysłu', 'verbose_name_plural': 'Zdjęcia pomysłów'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-start'], 'verbose_name': 'Rezerwacja', 'verbose_name_plural': 'Rezerwacje'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Usługa', 'verbose_name_plural': 'Usługi'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Slot czasowy', 'verbose_name_plural': 'Sloty czasowe'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil użytkownika', 'verbose_name_plural': 'Profile użytkowników'},
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'E-mail')], default='email', max_length=10, verbose_name='Kanał'),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='code',
            field=models.CharField(default='000000', max_length=6, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Utworzony'),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Wygasa'),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Użyty'),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Użyty o'),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_codes', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='ideaimage',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ideas.idea', verbose_name='Pomysł'),
        ),
        migrations.AlterField(
            model_name='ideaimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='idea_images/', validators=[ideas.models.validate_file_size], verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='ideaimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data przesłania'),
        ),
        migrations.AlterField(
            model_name='ideaimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL, verbose_name='Przesłane przez'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Kod potwierdzenia'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_email',
            field=models.EmailField(max_length=254, verbose_name='E-mail klienta'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Imię klienta'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nazwisko klienta'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefon klienta'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.DateTimeField(verbose_name='Koniec'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_guest',
            field=models.BooleanField(default=False, verbose_name='Rezerwacja gościa'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notatki'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='ideas.service', verbose_name='Usługa'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.DateTimeField(verbose_name='Początek'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekująca'), ('confirmed', 'Potwierdzona'), ('cancelled', 'Anulowana')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='Czas trwania (min)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end',
            field=models.DateTimeField(verbose_name='Koniec'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='ideas.service', verbose_name='Usługa'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start',
            field=models.DateTimeField(verbose_name='Początek'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data aktywacji'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='E-mail zweryfikowany'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='Telefon zweryfikowany'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('both', 'Oba')], default='email', max_length=10, verbose_name='Preferowany kontakt'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
