# Generated by Django 5.2.8 on 2025-12-15 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_alter_activationcode_options_alter_idea_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_note',
            field=models.TextField(blank=True, verbose_name='Notatka odwołania'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('change_plans', 'Zmiana planów'), ('illness', 'Choroba'), ('cannot_attend', 'Nie mogę się stawić'), ('staff_cancelled', 'Odwołane przez salon'), ('other', 'Inny powód')], max_length=50, verbose_name='Powód odwołania'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Token odwołania'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_token_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token wygasa'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data odwołania'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Odwołane przez'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_by_staff',
            field=models.BooleanField(default=False, verbose_name='Odwołane przez obsługę'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekująca'), ('confirmed', 'Potwierdzona'), ('cancelled', 'Anulowana'), ('completed', 'Zrealizowana'), ('no_show', 'Nieobecność')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
