# Generated by Django 5.2.8 on 2025-12-16 07:53

import django.db.models.deletion
import django.utils.timezone
import ideas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0011_reservation_cancellation_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
            ],
            options={
                'verbose_name': 'Kategoria usług',
                'verbose_name_plural': 'Kategorie usług',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/%Y/%m/', validators=[ideas.models.validate_file_size], verbose_name='Zdjęcie')),
                ('alt_text', models.CharField(blank=True, help_text='Opis zdjęcia dla dostępności (alt)', max_length=200, verbose_name='Tekst alternatywny')),
                ('is_primary', models.BooleanField(default=False, help_text='Główne zdjęcie wyświetlane na kafelku', verbose_name='Główne zdjęcie')),
                ('order', models.PositiveIntegerField(default=0, help_text='Kolejność w galerii', verbose_name='Kolejność')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Zdjęcie usługi',
                'verbose_name_plural': 'Zdjęcia usług',
                'ordering': ['-is_primary', 'order', '-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Usługa', 'verbose_name_plural': 'Usługi'},
        ),
        migrations.AddField(
            model_name='service',
            name='booking_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Liczba rezerwacji'),
        ),
        migrations.AddField(
            model_name='service',
            name='color',
            field=models.CharField(default='#007bff', help_text='Kolor HEX dla kalendarza (np. #FF5733)', max_length=7, verbose_name='Kolor'),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data utworzenia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='description_full',
            field=models.TextField(blank=True, help_text='Szczegółowy opis usługi, markdown support', verbose_name='Pełny opis'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_short',
            field=models.CharField(blank=True, help_text='2-3 zdania, widoczne na kafelku', max_length=255, verbose_name='Krótki opis'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='Nazwa ikony z FontAwesome/Material Icons (np. fa-cut, fa-palette)', max_length=50, verbose_name='Ikona'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywna'),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Kolejność'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='ideas.servicecategory', verbose_name='Kategoria'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'order'], name='ideas_servi_is_acti_b2da8a_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active'], name='ideas_servi_categor_1d9a7c_idx'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ideas.service', verbose_name='Usługa'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_images', to=settings.AUTH_USER_MODEL, verbose_name='Dodane przez'),
        ),
        migrations.AddIndex(
            model_name='serviceimage',
            index=models.Index(fields=['service', 'is_primary'], name='ideas_servi_service_9e170e_idx'),
        ),
    ]
