# Generated by Django 5.2.8 on 2025-12-16 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0012_servicecategory_serviceimage_alter_service_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start'], 'verbose_name': 'Slot czasowy', 'verbose_name_plural': 'Sloty czasowe'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='timeslot',
            field=models.ForeignKey(blank=True, help_text='Powiązany slot czasowy (nowy system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_slot', to='ideas.timeslot', verbose_name='Slot czasowy'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='block_note',
            field=models.TextField(blank=True, help_text='Widoczne tylko dla obsługi', verbose_name='Notatka blokady'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='block_reason',
            field=models.CharField(blank=True, choices=[('vacation', 'Urlop'), ('break', 'Przerwa'), ('training', 'Szkolenie'), ('maintenance', 'Konserwacja'), ('other', 'Inny powód')], max_length=20, verbose_name='Powód blokady'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timeslots', to=settings.AUTH_USER_MODEL, verbose_name='Utworzone przez'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Czy slot został utworzony przez szablon cykliczny', verbose_name='Cykliczny'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='recurring_group_id',
            field=models.CharField(blank=True, db_index=True, help_text='UUID identyfikujący grupę cyklicznie utworzonych slotów', max_length=50, verbose_name='ID grupy cyklicznej'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status',
            field=models.CharField(choices=[('available', 'Dostępny'), ('booked', 'Zajęty'), ('blocked', 'Zablokowany')], default='available', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.CreateModel(
            name='RecurringSlotTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa szablonu')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('monday', models.BooleanField(default=True, verbose_name='Poniedziałek')),
                ('tuesday', models.BooleanField(default=True, verbose_name='Wtorek')),
                ('wednesday', models.BooleanField(default=True, verbose_name='Środa')),
                ('thursday', models.BooleanField(default=True, verbose_name='Czwartek')),
                ('friday', models.BooleanField(default=True, verbose_name='Piątek')),
                ('saturday', models.BooleanField(default=False, verbose_name='Sobota')),
                ('sunday', models.BooleanField(default=False, verbose_name='Niedziela')),
                ('start_time', models.TimeField(default='09:00', verbose_name='Godzina rozpoczęcia')),
                ('end_time', models.TimeField(default='17:00', verbose_name='Godzina zakończenia')),
                ('slot_interval_minutes', models.PositiveIntegerField(default=30, verbose_name='Interwał slotów (min)')),
                ('breaks', models.JSONField(blank=True, default=list, verbose_name='Przerwy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Utworzone przez')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_templates', to='ideas.service', verbose_name='Usługa')),
            ],
            options={
                'verbose_name': 'Szablon cyklicznych slotów',
                'verbose_name_plural': 'Szablony cyklicznych slotów',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='timeslot',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_slots', to='ideas.recurringslottemplate', verbose_name='Szablon'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['service', 'start', 'status'], name='ideas_times_service_c0d910_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['status', 'start'], name='ideas_times_status_21701f_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['recurring_group_id'], name='ideas_times_recurri_f7be79_idx'),
        ),
    ]
