# Generated by Django 5.2.8 on 2025-12-16 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0013_alter_timeslot_options_reservation_timeslot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Pozostaw puste dla blokady dotyczącej wszystkich usług', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='ideas.service', verbose_name='Usługa'),
        ),
    ]
