# Generated by Django 5.2.8 on 2025-12-16 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0014_timeslot_service_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_channel', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('both', 'Oba')], default='email', max_length=10, verbose_name='Preferowany kanał')),
                ('enable_booking_confirmation', models.BooleanField(default=True, help_text='Nie można wyłączyć - wymagane', verbose_name='Potwierdzenie rezerwacji')),
                ('enable_booking_cancellation', models.BooleanField(default=True, help_text='Nie można wyłączyć - wymagane', verbose_name='Potwierdzenie odwołania')),
                ('enable_reminder_24h', models.BooleanField(default=True, verbose_name='Przypomnienie 24h przed wizytą')),
                ('enable_reminder_2h', models.BooleanField(default=True, verbose_name='Przypomnienie 2h przed wizytą')),
                ('enable_booking_changes', models.BooleanField(default=True, verbose_name='Powiadomienia o zmianach w wizycie')),
                ('enable_marketing', models.BooleanField(default=False, verbose_name='Oferty promocyjne i marketing')),
                ('enable_newsletter', models.BooleanField(default=False, verbose_name='Newsletter')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='np. 22:00', null=True, verbose_name='Początek godzin ciszy')),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='np. 08:00', null=True, verbose_name='Koniec godzin ciszy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Preferencje powiadomień',
                'verbose_name_plural': 'Preferencje powiadomień',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('verification_code', 'Kod weryfikacyjny'), ('booking_confirmation', 'Potwierdzenie rezerwacji'), ('booking_reminder_24h', 'Przypomnienie 24h'), ('booking_reminder_2h', 'Przypomnienie 2h'), ('booking_cancelled', 'Odwołanie wizyty'), ('booking_modified', 'Zmiana w wizycie'), ('staff_new_booking', 'Nowa rezerwacja (obsługa)'), ('staff_cancellation', 'Odwołanie przez klienta (obsługa)'), ('staff_daily_report', 'Raport dzienny'), ('staff_weekly_report', 'Raport tygodniowy')], max_length=50, verbose_name='Typ powiadomienia')),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('push', 'Push notification')], max_length=10, verbose_name='Kanał')),
                ('recipient', models.CharField(help_text='Email lub numer telefonu', max_length=255, verbose_name='Odbiorca')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Temat')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('html_message', models.TextField(blank=True, help_text='Opcjonalnie dla email', verbose_name='Wiadomość HTML')),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('sent', 'Wysłane'), ('delivered', 'Dostarczone'), ('failed', 'Nieudane'), ('cancelled', 'Anulowane')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Komunikat błędu')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Liczba ponowień')),
                ('related_object_type', models.CharField(blank=True, help_text='np. Reservation, ActivationCode', max_length=50, verbose_name='Typ powiązanego obiektu')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID powiązanego obiektu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Data wysłania')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Data dostarczenia')),
                ('opened_at', models.DateTimeField(blank=True, help_text='Dla email - tracking piksela', null=True, verbose_name='Data otwarcia')),
                ('clicked_at', models.DateTimeField(blank=True, help_text='Dla email - tracking linków', null=True, verbose_name='Data kliknięcia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Powiadomienie',
                'verbose_name_plural': 'Powiadomienia',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='ideas_notif_user_id_f6ae16_idx'), models.Index(fields=['status', 'created_at'], name='ideas_notif_status_958b42_idx'), models.Index(fields=['notification_type', 'created_at'], name='ideas_notif_notific_4384ed_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='ideas_notif_related_1dd868_idx')],
            },
        ),
    ]
