# Generated by Django 5.2.8 on 2025-12-16 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0015_notificationpreference_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer_segment',
            field=models.CharField(choices=[('new', 'Nowy (< 3 wizyty)'), ('regular', 'Regularny (3-9 wizyt)'), ('vip', 'VIP (10+ wizyt)'), ('at_risk', 'Zagrożony (brak wizyty > 90 dni)'), ('problematic', 'Problematyczny (>50% odwołań)')], default='new', help_text='Automatycznie aktualizowany', max_length=20, verbose_name='Segment klienta'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by', to='ideas.service', verbose_name='Ulubiona usługa'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_visit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data ostatniej wizyty'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff_notes',
            field=models.TextField(blank=True, help_text='Widoczne tylko dla obsługi - preferencje, uwagi, alergie', verbose_name='Notatki obsługi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Łączne wydatki (PLN)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_visits',
            field=models.PositiveIntegerField(default=0, verbose_name='Łączna liczba wizyt'),
        ),
        migrations.CreateModel(
            name='ReservationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Notatka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('is_important', models.BooleanField(default=False, help_text='Np. alergie, wymagania specjalne', verbose_name='Ważna')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notes', to='ideas.reservation', verbose_name='Rezerwacja')),
            ],
            options={
                'verbose_name': 'Notatka obsługi',
                'verbose_name_plural': 'Notatki obsługi',
                'ordering': ['-created_at'],
            },
        ),
    ]
